# Generated by Django 5.1.1 on 2024-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cropimage_remove_crop_images_urls_crop_images_urls"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cropimage",
            name="url",
        ),
        migrations.AddField(
            model_name="cropimage",
            name="source",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="crop",
            name="cover_img_url",
            field=models.ImageField(upload_to=""),
        ),
    ]
