# Generated by Django 5.1.1 on 2024-09-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_cropimage_url_cropimage_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmer",
            name="profile_pic_url",
        ),
        migrations.AddField(
            model_name="farmer",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="preferred_quantity_unit",
            field=models.CharField(choices=[("kg", "Kilograms")], max_length=20),
        ),
    ]
