# Generated by Django 5.1.1 on 2024-09-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_farmer_profile_pic_url_farmer_profile_pic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="profile_pic_url",
        ),
        migrations.AddField(
            model_name="buyer",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
