# Generated by Django 5.1.1 on 2024-09-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_buyer_profile_pic_url_buyer_profile_pic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crop",
            old_name="cover_img_url",
            new_name="cover_img",
        ),
        migrations.RenameField(
            model_name="crop",
            old_name="images_urls",
            new_name="images",
        ),
    ]
